# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import check_pb2 as check__pb2


class ValidationServiceStub(object):
    """string data = 1;
    }

    message EconResponse { string result_key = 1; }

    service EconService { rpc ProcessData(EconRequest) returns (EconResponse); }

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessData = channel.unary_unary(
                '/econ.ValidationService/ProcessData',
                request_serializer=check__pb2.ValidationRequest.SerializeToString,
                response_deserializer=check__pb2.ValidationResponse.FromString,
                )


class ValidationServiceServicer(object):
    """string data = 1;
    }

    message EconResponse { string result_key = 1; }

    service EconService { rpc ProcessData(EconRequest) returns (EconResponse); }

    """

    def ProcessData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessData,
                    request_deserializer=check__pb2.ValidationRequest.FromString,
                    response_serializer=check__pb2.ValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'econ.ValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidationService(object):
    """string data = 1;
    }

    message EconResponse { string result_key = 1; }

    service EconService { rpc ProcessData(EconRequest) returns (EconResponse); }

    """

    @staticmethod
    def ProcessData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/econ.ValidationService/ProcessData',
            check__pb2.ValidationRequest.SerializeToString,
            check__pb2.ValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
