# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63heck.proto\x12\x04\x65\x63on\"\xae\x01\n\x11ValidationRequest\x12\x10\n\x08passport\x18\x01 \x01(\t\x12\x14\n\x0cregistration\x18\x02 \x01(\t\x12\x11\n\tresidence\x18\x03 \x01(\t\x12\x1c\n\x14presence_of_children\x18\x04 \x01(\t\x12\x0b\n\x03job\x18\x05 \x01(\t\x12\x0e\n\x06salary\x18\x06 \x01(\t\x12\x13\n\x0b\x62ride_price\x18\x07 \x01(\t\x12\x0e\n\x06saving\x18\x08 \x01(\t\"\xaf\x01\n\x12ValidationResponse\x12\x10\n\x08passport\x18\x01 \x01(\x08\x12\x14\n\x0cregistration\x18\x02 \x01(\x08\x12\x11\n\tresidence\x18\x03 \x01(\x08\x12\x1c\n\x14presence_of_children\x18\x04 \x01(\x08\x12\x0b\n\x03job\x18\x05 \x01(\x08\x12\x0e\n\x06salary\x18\x06 \x01(\x08\x12\x13\n\x0b\x62ride_price\x18\x07 \x01(\x08\x12\x0e\n\x06saving\x18\x08 \x01(\x08\x32U\n\x11ValidationService\x12@\n\x0bProcessData\x12\x17.econ.ValidationRequest\x1a\x18.econ.ValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'check_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALIDATIONREQUEST']._serialized_start=22
  _globals['_VALIDATIONREQUEST']._serialized_end=196
  _globals['_VALIDATIONRESPONSE']._serialized_start=199
  _globals['_VALIDATIONRESPONSE']._serialized_end=374
  _globals['_VALIDATIONSERVICE']._serialized_start=376
  _globals['_VALIDATIONSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
