# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ValidatorService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ValidatorService.proto\"\x8e\x01\n\x10ValidatorRequest\x12\x41\n\x10\x64ocumentContents\x18\x01 \x03(\x0b\x32\'.ValidatorRequest.DocumentContentsEntry\x1a\x37\n\x15\x44ocumentContentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x98\x01\n\x12ResultOfValidation\x12G\n\x12resultOfValidation\x18\x01 \x03(\x0b\x32+.ResultOfValidation.ResultOfValidationEntry\x1a\x39\n\x17ResultOfValidationEntry\x12\x0b\n\x03key\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa8\x01\n\x11ValidatorResponse\x12\x44\n\x11validationResults\x18\x01 \x03(\x0b\x32).ValidatorResponse.ValidationResultsEntry\x1aM\n\x16ValidationResultsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.ResultOfValidation:\x02\x38\x01\x32L\n\x10ValidatorService\x12\x38\n\x0fValidateRequest\x12\x11.ValidatorRequest\x1a\x12.ValidatorResponseBA\n&ru.sberbank.sbervalidator.service.grpcB\x15ValidatorServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ValidatorService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&ru.sberbank.sbervalidator.service.grpcB\025ValidatorServiceProtoP\001'
  _VALIDATORREQUEST_DOCUMENTCONTENTSENTRY._options = None
  _VALIDATORREQUEST_DOCUMENTCONTENTSENTRY._serialized_options = b'8\001'
  _RESULTOFVALIDATION_RESULTOFVALIDATIONENTRY._options = None
  _RESULTOFVALIDATION_RESULTOFVALIDATIONENTRY._serialized_options = b'8\001'
  _VALIDATORRESPONSE_VALIDATIONRESULTSENTRY._options = None
  _VALIDATORRESPONSE_VALIDATIONRESULTSENTRY._serialized_options = b'8\001'
  _globals['_VALIDATORREQUEST']._serialized_start=27
  _globals['_VALIDATORREQUEST']._serialized_end=169
  _globals['_VALIDATORREQUEST_DOCUMENTCONTENTSENTRY']._serialized_start=114
  _globals['_VALIDATORREQUEST_DOCUMENTCONTENTSENTRY']._serialized_end=169
  _globals['_RESULTOFVALIDATION']._serialized_start=172
  _globals['_RESULTOFVALIDATION']._serialized_end=324
  _globals['_RESULTOFVALIDATION_RESULTOFVALIDATIONENTRY']._serialized_start=267
  _globals['_RESULTOFVALIDATION_RESULTOFVALIDATIONENTRY']._serialized_end=324
  _globals['_VALIDATORRESPONSE']._serialized_start=327
  _globals['_VALIDATORRESPONSE']._serialized_end=495
  _globals['_VALIDATORRESPONSE_VALIDATIONRESULTSENTRY']._serialized_start=418
  _globals['_VALIDATORRESPONSE_VALIDATIONRESULTSENTRY']._serialized_end=495
  _globals['_VALIDATORSERVICE']._serialized_start=497
  _globals['_VALIDATORSERVICE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
